package Practice03.num_1;

import java.util.Random;
import java.util.Scanner;

public class Tester {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter the size of array: ");
        int size = sc.nextInt();
        int[] mas = new int[size];
        int[] mas1 = new int[size];
        Random rand = new Random();
        for(int i = 0; i< size; i++)
        {
            mas[i] = rand.nextInt(1000);
            mas1[i] = (int) (Math.random() * ((1000 - 0) - 1)) + 0;
        }
        System.out.println("Array generated by the class Random: ");
        for(int i = 0; i < size; i++)
        {
            System.out.println(mas[i]);
        }
        System.out.println("Array generated by the method of class Random: ");
        for(int i = 0; i < size; i++)
        {
            System.out.println(mas1[i]);
        }

    }
}
